Repository witty-mind/github-actions-demo, pull requests merged in 2021-03, with the labels that each got.

#1 my number commit
  app/src/main/java/com/debasish/github_actions_demo/MainActivity.java
Labels: enhancement

#2 my number commit (#1)
  app/src/main/java/com/debasish/github_actions_demo/MainActivity.java
Labels: bug

#3 Added Github Work flow
  .github/workflow/android.yml
  .idea/gradle.xml
Labels: size/M

#4 Create main.yml
  .github/workflows/main.yml
Labels: size/M
